local function feed(keys)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(keys, true, false, true), "xt", false)
  vim.wait(30)
end

local function run(case)
  local buf = vim.api.nvim_create_buf(true, false)
  vim.api.nvim_set_current_buf(buf)
  vim.bo.filetype = case.filetype
  vim.api.nvim_buf_set_lines(buf, 0, -1, false,
    type(case.before) == "table" and case.before or { case.before or "" })
  assert(vim.wait(120000, function()
    local ok, parser = pcall(vim.treesitter.get_parser, buf)
    return ok and parser ~= nil and pcall(function() parser:parse() end)
  end, 100), case.filetype .. " parser was not installed")
  vim.api.nvim_win_set_cursor(0, { case.row or 1, case.column or 0 })
  if type(case.keys) == "table" then
    for _, keys in ipairs(case.keys) do feed(keys) end
  else
    feed(case.keys)
  end
  if case.rename then
    vim.api.nvim_exec_autocmds("TextChanged", { buffer = buf })
  end
  local actual = type(case.expected) == "table"
    and vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    or vim.api.nvim_get_current_line()
  return vim.deep_equal(actual, case.expected),
    case.label .. ": expected " .. vim.inspect(case.expected)
      .. ", got " .. vim.inspect(actual)
end

local cases = {
  { label = "TSX self-closing custom component", filetype = "typescriptreact",
    keys = "i<MenuComponent /><Esc>", expected = "<MenuComponent />" },
  { label = "TSX custom component pair", filetype = "typescriptreact",
    keys = "i<MenuComponent><Esc>",
    expected = "<MenuComponent></MenuComponent>" },
  { label = "TSX custom component rename", filetype = "typescriptreact",
    before = "<MenuComponent></MenuComponent>", column = 2,
    keys = { "ciwPanel", "<Esc>" }, rename = true,
    expected = "<Panel></Panel>" },
  { label = "TSX member component and expression", filetype = "typescriptreact",
    keys = "i<Menu.Item active={left > right}><Esc>",
    expected = "<Menu.Item active={left > right}></Menu.Item>" },
  { label = "TSX member component rename", filetype = "typescriptreact",
    before = "<Menu.Item></Menu.Item>", column = 7,
    keys = { "ciwLink", "<Esc>" }, rename = true,
    expected = "<Menu.Link></Menu.Link>" },
  { label = "TSX member closing-side rename", filetype = "typescriptreact",
    before = "<Menu.Item></Menu.Item>", column = 18,
    keys = { "ciwLink", "<Esc>" }, rename = true,
    expected = "<Menu.Link></Menu.Link>" },
  { label = "TSX namespaced element", filetype = "typescriptreact",
    keys = "i<svg:path><Esc>", expected = "<svg:path></svg:path>" },
  { label = "TSX dollar-prefixed component", filetype = "typescriptreact",
    keys = "i<$Panel><Esc>", expected = "<$Panel></$Panel>" },
  { label = "TSX dollar-prefixed component rename", filetype = "typescriptreact",
    before = "<$Panel></$Panel>", column = 3,
    keys = { "ciw$Card", "<Esc>" }, rename = true,
    expected = "<$Card></$Card>" },
  { label = "TSX multiline component props", filetype = "typescriptreact",
    before = { "<Menu.Item", "  active={left > right}", "" }, row = 3,
    keys = "i><Esc>",
    expected = { "<Menu.Item", "  active={left > right}", "></Menu.Item>" } },
  { label = "TSX component with nested JSX expression", filetype = "typescriptreact",
    keys = "i<MenuComponent icon={<Icon />} /><Esc>",
    expected = "<MenuComponent icon={<Icon />} />" },
  { label = "TSX shorthand fragment", filetype = "typescriptreact",
    keys = "i<><Esc>", expected = "<></>" },
  { label = "TSX nested shorthand fragment", filetype = "typescriptreact",
    before = "<></>", column = 1, keys = "a<><Esc>",
    expected = "<><></></>" },
  { label = "JSX shorthand fragment", filetype = "javascriptreact",
    keys = "i<><Esc>", expected = "<></>" },
  { label = "TSX same-name component child", filetype = "typescriptreact",
    before = "<MenuComponent></MenuComponent>", column = 14,
    keys = "a<MenuComponent><Esc>",
    expected = "<MenuComponent><MenuComponent></MenuComponent></MenuComponent>" },
  { label = "TSX generic type parameters", filetype = "typescriptreact",
    keys = "iconst identity = <T,>(value: T) => value;<Esc>",
    expected = "const identity = <T,>(value: T) => value;" },
  { label = "TSX comparison", filetype = "typescriptreact",
    keys = "iconst result = left < right ? left : right;<Esc>",
    expected = "const result = left < right ? left : right;" },
  { label = "TSX string containing markup", filetype = "typescriptreact",
    keys = 'iconst label = "<MenuComponent>";<Esc>',
    expected = 'const label = "<MenuComponent>";' },
  { label = "HTML same-name child", filetype = "html",
    before = "<div></div>", column = 4, keys = "a<div><Esc>",
    expected = "<div><div></div></div>" },
  { label = "HTML custom element", filetype = "html",
    keys = "i<menu-panel><Esc>", expected = "<menu-panel></menu-panel>" },
  { label = "HTML SVG foreign element", filetype = "html",
    keys = "i<linearGradient><Esc>",
    expected = "<linearGradient></linearGradient>" },
  { label = "HTML quoted angle bracket", filetype = "html",
    keys = 'i<a title="A > B"><Esc>',
    expected = '<a title="A > B"></a>' },
  { label = "HTML closing-side rename with attributes", filetype = "html",
    before = '<div class="card" data-label="A > B"></div>',
    column = #'<div class="card" data-label="A > B"></',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<section class="card" data-label="A > B"></section>' },
  { label = "HTML script closing-side rename with src attribute",
    filetype = "html", before = '<script src=""></script>',
    column = #'<script src=""></', keys = { "ciwstyle", "<Esc>" },
    rename = true, expected = '<style src=""></style>' },
  { label = "HTML script closing-side rename inside a parent",
    filetype = "html", before = '<body><script src="app.js"></script></body>',
    column = #'<body><script src="app.js"></',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<body><section src="app.js"></section></body>' },
  { label = "HTML script closing-side rename before a sibling",
    filetype = "html", before = '<script src="app.js"></script><main>ok</main>',
    column = #'<script src="app.js"></',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<section src="app.js"></section><main>ok</main>' },
  { label = "HTML script closing-side rename after inline content",
    filetype = "html",
    before = '<script src="app.js">const label = "x";</script>',
    column = #'<script src="app.js">const label = "x";</',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<section src="app.js">const label = "x";</section>' },
  { label = "HTML style closing-side rename with media attribute",
    filetype = "html", before = '<style media="print"></style>',
    column = #'<style media="print"></',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<section media="print"></section>' },
  { label = "HTML unmatched style comment is not a closing tag",
    filetype = "html", before = '<style media="print">/* </section> */',
    column = #'<style media="print">/* </',
    keys = { "ciwarticle", "<Esc>" }, rename = true,
    expected = '<style media="print">/* </article> */' },
  { label = "HTML script text resembling a different closing tag",
    filetype = "html",
    before = '<script src="">const text = "</style>";</script>',
    column = #'<script src="">const text = "</',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<script src="">const text = "</section>";</script>' },
  { label = "HTML unmatched script string is not a closing tag",
    filetype = "html",
    before = '<script src="">const text = "</style>";',
    column = #'<script src="">const text = "</',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<script src="">const text = "</section>";' },
  { label = "HTML unmatched script comment is not a closing tag",
    filetype = "html", before = '<script src="">// </style>',
    column = #'<script src="">// </',
    keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = '<script src="">// </section>' },
  { label = "HTML closing-side rename with multiline attributes and child",
    filetype = "html",
    before = { '<div', '  class="card">', '  <span>content</span>', '</div>' },
    row = 4, column = 2, keys = { "ciwsection", "<Esc>" }, rename = true,
    expected = { '<section', '  class="card">', '  <span>content</span>',
      '</section>' } },
  { label = "HTML angle bracket edited inside existing attribute", filetype = "html",
    before = '<a title="A B"></a>', column = 12,
    keys = "i><Esc>", expected = '<a title="A >B"></a>' },
  { label = "HTML angle bracket in unpaired existing attribute", filetype = "html",
    before = '<a title="A B">', column = 12,
    keys = "i><Esc>", expected = '<a title="A >B">' },
  { label = "HTML void element", filetype = "html",
    keys = "i<img src=\"logo.svg\"><Esc>", expected = '<img src="logo.svg">' },
  { label = "XML case sensitive pair", filetype = "xml",
    keys = "i<Item><Esc>", expected = "<Item></Item>" },
  { label = "XML self-closing element", filetype = "xml",
    keys = "i<Item /><Esc>", expected = "<Item />" },
  { label = "XML namespaced element", filetype = "xml",
    keys = "i<ui:Item><Esc>", expected = "<ui:Item></ui:Item>" },
  { label = "XML non-ASCII name", filetype = "xml",
    keys = "i<Элемент><Esc>", expected = "<Элемент></Элемент>" },
  { label = "XML non-ASCII name rename", filetype = "xml",
    before = "<Элемент></Элемент>", column = 2,
    keys = { "ciwУзел", "<Esc>" }, rename = true,
    expected = "<Узел></Узел>" },
  { label = "HTML optional list item closes during parent rename", filetype = "html",
    before = "<ul><li>one<li>two</ul>", column = 2,
    keys = { "ciwol", "<Esc>" }, rename = true,
    expected = "<ol><li>one<li>two</ol>" },
  { label = "HTML optional list item closes during closing-side rename", filetype = "html",
    before = "<ul><li>one<li>two</ul>", column = 21,
    keys = { "ciwol", "<Esc>" }, rename = true,
    expected = "<ol><li>one<li>two</ol>" },
  { label = "HTML implicit paragraph closes during parent rename", filetype = "html",
    before = "<section><p>one<p>two</section>", column = 2,
    keys = { "ciwmain", "<Esc>" }, rename = true,
    expected = "<main><p>one<p>two</main>" },
  { label = "HTML option ends during select rename", filetype = "html",
    before = "<select><option>A<option>B</select>", column = 3,
    keys = { "ciwdatalist", "<Esc>" }, rename = true,
    expected = "<datalist><option>A<option>B</datalist>" },
  { label = "HTML omitted table cell and row ends", filetype = "html",
    before = "<table><tbody><tr><td>A<td>B</tbody></table>", column = 9,
    keys = { "ciwthead", "<Esc>" }, rename = true,
    expected = "<table><thead><tr><td>A<td>B</thead></table>" },
  { label = "HTML explicit paragraph closer renames to block tag", filetype = "html",
    before = "<p><span>text</span></p>", column = 22,
    keys = { "ciwdiv", "<Esc>" }, rename = true,
    expected = "<div><span>text</span></div>" },
  { label = "HTML comment containing markup", filetype = "html",
    before = "<!--  -->", column = 4, keys = "a<div><Esc>",
    expected = "<!-- <div> -->" },
  { label = "Markdown inline code containing markup", filetype = "markdown",
    before = "``", column = 0, keys = "a<div><Esc>",
    expected = "`<div>`" },
  { label = "Markdown fenced code containing markup", filetype = "markdown",
    before = { "```html", "", "```" }, row = 2,
    keys = "i<div><Esc>", expected = { "```html", "<div>", "```" } },
  { label = "Markdown embedded HTML", filetype = "markdown",
    keys = "i<div><Esc>", expected = "<div></div>" },
  { label = "Vue custom component", filetype = "vue",
    keys = "i<MenuComponent><Esc>",
    expected = "<MenuComponent></MenuComponent>" },
  { label = "Django HTML template block", filetype = "htmldjango",
    before = "{% if active %}{% endif %}", column = 15,
    keys = "i<strong><Esc>",
    expected = "{% if active %}<strong></strong>{% endif %}" },
  { label = "Vue dynamic attribute", filetype = "vue",
    keys = 'i<MenuComponent :value="a > b"><Esc>',
    expected = '<MenuComponent :value="a > b"></MenuComponent>' },
  { label = "Svelte custom component", filetype = "svelte",
    keys = "i<MenuComponent /><Esc>", expected = "<MenuComponent />" },
  { label = "Svelte event directive", filetype = "svelte",
    keys = "i<MenuComponent on:click={handler}><Esc>",
    expected = "<MenuComponent on:click={handler}></MenuComponent>" },
}

local failures = {}
for _, case in ipairs(cases) do
  local ok, result, message = pcall(run, case)
  if not ok then
    failures[#failures + 1] = case.label .. ": " .. result
  elseif not result then
    failures[#failures + 1] = message
  end
end
assert(#failures == 0, table.concat(failures, "\n"))
print("Tag scenarios passed: " .. #cases)
